name: Generate and upload release assets

on:
  push:
    tags:
      - 'v*'

jobs:
  upload:
    name: Upload Artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: shell-lib/docker/install_docker.sh
      - run: installer/generate_installer.sh
      - uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          generate_release_notes: true
          prerelease: ${{ contains(github.ref_name, '-') }}
          files: |
            installer/BeaKer.tar
            agent/install-sysmon-beats.ps1
