- name: "BeaKer Install: BeaKer installer."
  hosts: "{{ install_hosts }}"
  become: true

  vars:
    beaker_version: "REPLACE_ME"
    # TODO: container name variables
    beaker_container_images:
      - "taskrabbit/elasticsearch-dump:v6.28.0"
      # - "activecm-beaker/check_kibana:latest"
      - "elasticsearch:8.17.10"
      - "kibana:8.17.10"
    ansible_python_interpreter: /bin/python3

  # The install_pre.yml script should already have been run by this point

  tasks:
    #Make directories
    - name: "BeaKer Install: Create configuration directories."
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
        mode: 0755
      loop:
        - /etc/BeaKer/
        - /opt/BeaKer/
        - /var/BeaKer/
      tags:
        - docker
        - beaker
        - linux
        - linuxdeb
        - linuxrpm

    - name: "BeaKer Install: Transfer configuration files to /etc/BeaKer."
      copy:
        src: "./files/etc/"
        dest: /etc/BeaKer/
        owner: root
        group: root
        mode: 0755
      tags:
        - docker
        - beaker
        - linux
        - linuxdeb
        - linuxrpm

    - name: "BeaKer Install: Transfer installation files to /etc/BeaKer."
      copy:
        src: "./files/opt/"
        dest: /opt/BeaKer/
        owner: root
        group: root
        mode: 0755
      tags:
        - docker
        - beaker
        - linux
        - linuxdeb
        - linuxrpm

    - name: "BeaKer Install: Transfer BeaKer script to /usr/local/bin."
      copy:
        src: "/opt/BeaKer/beaker.sh"
        dest: /usr/local/bin/beaker
        owner: root
        group: root
        mode: 0755
      tags:
        - docker
        - beaker
        - linux
        - linuxdeb
        - linuxrpm

    - name: "BeaKer Install: Pull from GitHub Container Repository."
      community.docker.docker_image:
        name: "{{ item }}"
        source: pull
        force_source: true
      loop: "{{ beaker_container_images }}"
      tags:
        - docker
        - beaker
        - linux
        - linuxdeb
        - linuxrpm

    - name: "BeaKer Install: Create snapshots directory."
      ansible.builtin.file:
        path: "/var/BeaKer/snapshots"
        state: directory
        owner: root
        group: root
        mode: 0777
      tags:
        - docker
        - beaker
        - linux
        - linuxdeb
        - linuxrpm

    - name: "BeaKer Install: Check for and create certificates."
      block:
        # Make sure certs don't exist before continuing
        - name: "BeaKer Install: Check if certificates already exist."
          stat:
            path: "/etc/BeaKer/certificates/{{ item }}"
          with_items:
            - "ca/ca.crt"
            - "ca/ca.key"
            - "instance/instance.crt"
            - "instance/instance.key"
          register: check_cert_files

        - name: "BeaKer Install: Generate ELK certificate authority certificate."
          command: "{{ item }}"
          with_items:
            - "rm -rf /etc/BeaKer/certificates/ca"
            - "beaker run --rm --user root elasticsearch elasticsearch-certutil ca --pem --days 10950 --out /usr/share/elasticsearch/config/certificates/ca.zip > /dev/null"
            - "unzip /etc/BeaKer/certificates/ca.zip -d /etc/BeaKer/certificates"
            - "rm /etc/BeaKer/certificates/ca.zip"
          when: ((crt_stat|length==0) or not crt_stat.0.stat.exists) or ((key_stat|length==0) or not key_stat.0.stat.exists)
          vars:
            crt_stat: "{{ (check_cert_files.results | selectattr('item', 'equalto', 'ca/ca.crt')) }}"
            key_stat: "{{ (check_cert_files.results | selectattr('item', 'equalto', 'ca/ca.key')) }}"

        - name: "BeaKer Install: Generate ELK certificate."
          command: "{{ item }}"
          with_items:
            - "rm -rf /etc/BeaKer/certificates/instance"
            - >-
              beaker run --rm --user root elasticsearch elasticsearch-certutil cert
              --ca-cert /usr/share/elasticsearch/config/certificates/ca/ca.crt
              --ca-key /usr/share/elasticsearch/config/certificates/ca/ca.key
              --pem --days 10950 --out /usr/share/elasticsearch/config/certificates/certs.zip > /dev/null
            - "unzip /etc/BeaKer/certificates/certs.zip -d /etc/BeaKer/certificates"
            - "rm /etc/BeaKer/certificates/certs.zip"
          when: ((crt_stat|length==0) or not crt_stat.0.stat.exists) or ((key_stat|length==0) or not key_stat.0.stat.exists)
          vars:
            crt_stat: "{{ (check_cert_files.results | selectattr('item', 'equalto', 'instance/instance.crt')) }}"
            key_stat: "{{ (check_cert_files.results | selectattr('item', 'equalto', 'instance/instance.key')) }}"

    - name: "Short circuit"
      fail:

    #    - name: "BeaKer Install: Start BeaKer"
    #      command: "beaker up -d"

    - name: "BeaKer Install: Wait for BeaKer Docker containers to be healthy"
      community.docker.docker_container_info:
        name: "{{ item }}"
      until: "container_info.container.State.Health.Status == 'healthy'"
      # register: container_info
      retries: 15
      delay: 10
      loop:
        - beaker-elasticsearch-1
        - beaker-kibana-1

    - name: "BeaKer Install: Wait for Elasticsearch API"
      uri:
        url: "https://localhost:9200"
        user: "elastic"
        password: "{{ elastic_password }}"
        # might need url_username/url_password if basic auth
        return_content: yes
      until: uri_output.status == 200
      retries: 10
      delay: 15

    - name: "BeaKer Install: Wait for Kibana API"
      uri:
        url: "https://localhost:5601/api/status"
        user: "elastic"
        password: "{{ elastic_password }}"
        # might need url_username/url_password if basic auth
        return_content: yes
      until: uri_output.status == 200
      retries: 10
      delay: 15
