- name: "BeaKer Install: BeaKer installer."
  hosts: "{{ install_hosts }}"
  become: true

  vars:
    beaker_version: "REPLACE_ME"
    # TODO: container name variables
    beaker_container_images:
      - "taskrabbit/elasticsearch-dump:v6.28.0"
      # - "activecm-beaker/check_kibana:latest"
      - "elasticsearch:8.17.10"
      - "kibana:8.17.10"
    ansible_python_interpreter: /bin/python3

  # The install_pre.yml script should already have been run by this point

  tasks:
    #Make directories
    - name: "BeaKer Install: Create configuration directories."
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
        mode: 0755
      loop:
        - /etc/BeaKer/
        - /opt/BeaKer/
        - /var/BeaKer/
      tags:
        - docker
        - beaker
        - linux
        - linuxdeb
        - linuxrpm

    - name: "BeaKer Install: Transfer configuration files to /etc/BeaKer."
      copy:
        src: "./files/etc/"
        dest: /etc/BeaKer/
        owner: root
        group: root
        mode: 0755
      tags:
        - docker
        - beaker
        - linux
        - linuxdeb
        - linuxrpm

    - name: "BeaKer Install: Transfer installation files to /etc/BeaKer."
      copy:
        src: "./files/opt/{{ item }}"
        dest: /opt/BeaKer/
        owner: root
        group: root
        mode: 0755
      with_items:
        - LICENSE
        - beaker.sh
        - docker-compose.yml
        - elasticsearch
        - kibana
      tags:
        - docker
        - beaker
        - linux
        - linuxdeb
        - linuxrpm

    - name: "BeaKer Install: Check if environment file exists."
      stat:
        path: "/opt/BeaKer/.env"
      register: env_file_stat

    - name: "BeaKer Install: Copy environment file to /opt/BeaKer."
      copy:
        src: "./files/opt/.env"
        dest: /opt/BeaKer/
        owner: root
        group: root
        mode: 0755
      when: env_file_stat.stat is not defined or not env_file_stat.stat.exists
      tags:
        - docker
        - beaker
        - linux
        - linuxdeb
        - linuxrpm

    - name: "BeaKer Install: Transfer BeaKer script to /usr/local/bin."
      copy:
        src: "/opt/BeaKer/beaker.sh"
        dest: /usr/local/bin/beaker
        owner: root
        group: root
        mode: 0755
      tags:
        - docker
        - beaker
        - linux
        - linuxdeb
        - linuxrpm

    - name: "BeaKer Install: Pull from GitHub Container Repository."
      community.docker.docker_image:
        name: "{{ item }}"
        source: pull
        force_source: true
      loop: "{{ beaker_container_images }}"
      tags:
        - docker
        - beaker
        - linux
        - linuxdeb
        - linuxrpm

    - name: "BeaKer Install: Create snapshots directory."
      ansible.builtin.file:
        path: "/var/BeaKer/snapshots"
        state: directory
        owner: root
        group: root
        mode: 0777
      tags:
        - docker
        - beaker
        - linux
        - linuxdeb
        - linuxrpm

    - name: "BeaKer Install: Check for and create certificates."
      block:
        # Make sure certs don't exist before continuing
        - name: "BeaKer Install: Check if certificates already exist."
          stat:
            path: "/etc/BeaKer/certificates/{{ item }}"
          with_items:
            - "ca/ca.crt"
            - "ca/ca.key"
            - "instance/instance.crt"
            - "instance/instance.key"
          register: check_cert_files

        - name: "BeaKer Install: Generate ELK certificate authority certificate."
          command: "{{ item }}"
          with_items:
            - "rm -rf /etc/BeaKer/certificates/ca"
            - "beaker run --rm --user root elasticsearch elasticsearch-certutil ca --pem --days 10950 --out /usr/share/elasticsearch/config/certificates/ca.zip > /dev/null"
            - "unzip /etc/BeaKer/certificates/ca.zip -d /etc/BeaKer/certificates"
            - "rm /etc/BeaKer/certificates/ca.zip"
          when: ((crt_stat|length==0) or not crt_stat.0.stat.exists) or ((key_stat|length==0) or not key_stat.0.stat.exists)
          vars:
            crt_stat: "{{ (check_cert_files.results | selectattr('item', 'equalto', 'ca/ca.crt')) }}"
            key_stat: "{{ (check_cert_files.results | selectattr('item', 'equalto', 'ca/ca.key')) }}"

        - name: "BeaKer Install: Generate ELK certificate."
          command: "{{ item }}"
          with_items:
            - "rm -rf /etc/BeaKer/certificates/instance"
            - >-
              beaker run --rm --user root elasticsearch elasticsearch-certutil cert
              --ca-cert /usr/share/elasticsearch/config/certificates/ca/ca.crt
              --ca-key /usr/share/elasticsearch/config/certificates/ca/ca.key
              --pem --days 10950 --out /usr/share/elasticsearch/config/certificates/certs.zip > /dev/null
            - "unzip /etc/BeaKer/certificates/certs.zip -d /etc/BeaKer/certificates"
            - "rm /etc/BeaKer/certificates/certs.zip"
          when: ((crt_stat|length==0) or not crt_stat.0.stat.exists) or ((key_stat|length==0) or not key_stat.0.stat.exists)
          vars:
            crt_stat: "{{ (check_cert_files.results | selectattr('item', 'equalto', 'instance/instance.crt')) }}"
            key_stat: "{{ (check_cert_files.results | selectattr('item', 'equalto', 'instance/instance.key')) }}"

    - name: "BeaKer Install: Generate random ELK encryption keys."
      ansible.builtin.replace:
        path: /opt/BeaKer/.env
        regexp: "^{{ item }}=$"
        replace: "{{ item }}={{ lookup('community.general.random_string', base64=True, length=64) }}"
      loop:
        - "SAVED_OBJECTS_ENCRYPTION_KEY"
        - "REPORTING_ENCRYPTION_KEY"
        - "SECURITY_ENCRYPTION_KEY"

    - name: "BeaKer Install: Generate random Elasticsearch password."
      set_fact:
        ELASTIC_PASSWORD: "{{ lookup('community.general.random_string', special=False, length=32) }}"

    - name: "BeaKer Install: Write Elasticsearch password to environment file."
      ansible.builtin.replace:
        path: /opt/BeaKer/.env
        regexp: "^ELASTIC_PASSWORD=$"
        replace: "ELASTIC_PASSWORD={{ ELASTIC_PASSWORD }}"

    - name: "BeaKer Install: Start BeaKer."
      command: "beaker up -d"

    - name: "BeaKer Install: Wait for BeaKer Elasticsearch Docker container to be healthy"
      community.docker.docker_container_info:
        name: "beaker-elasticsearch-1"
      until: "container_info.exists and container_info.container.State.Health.Status == 'healthy'"
      register: container_info
      retries: 15
      delay: 10

    - name: "BeaKer Install: Read Elasticsearch password from environment file."
      set_fact:
        ELASTIC_PASSWORD: "{{ lookup('file', '/opt/BeaKer/.env') | regex_search('ELASTIC_PASSWORD=(.+)\\n', '\\1') | first }}"

    - name: "BeaKer Install: Check for Kibana service token."
      ansible.builtin.uri:
        url: "https://localhost:9200/_security/service/elastic/kibana/credential"
        method: GET
        validate_certs: false
        user: "elastic"
        password: "{{ ELASTIC_PASSWORD }}"
      register: kb_token_lookup

    - name: "BeaKer Install: Create new Kibana service token."
      ansible.builtin.uri:
        url: "https://localhost:9200/_security/service/elastic/kibana/credential/token/kibana-beaker"
        method: POST
        validate_certs: false
        user: "elastic"
        password: "{{ ELASTIC_PASSWORD }}"
      when: kb_token_lookup.json.tokens["kibana-beaker"] is not defined
      register: kb_token_created

    - name: "BeaKer Install: Write Kibana service token to file."
      ansible.builtin.replace:
        path: /opt/BeaKer/.env
        regexp: "^KIBANA_SERVICE_TOKEN=$"
        replace: "KIBANA_SERVICE_TOKEN={{ kb_token_created.json.token.value }}"
      when: kb_token_lookup.json.tokens["kibana-beaker"] is not defined

    - name: "BeaKer Install: Load Kibana service token from environment file."
      set_fact:
        KIBANA_SERVICE_TOKEN: "{{ lookup('file', '/opt/BeaKer/.env') | regex_search('KIBANA_SERVICE_TOKEN=(.+)\\n', '\\1') | first }}"

    - name: "BeaKer Install: Restart BeaKer."
      command: "{{ item }}"
      with_items:
        - "beaker down"
        - "beaker up -d --force-recreate"

    - name: "BeaKer Install: Wait for BeaKer Docker containers to be healthy"
      community.docker.docker_container_info:
        name: "{{ item }}"
      until: "container_info.exists and container_info.container.State.Health.Status == 'healthy'"
      register: container_info
      with_items:
        - beaker-elasticsearch-1
        - beaker-kibana-1
      retries: 15
      delay: 10

    # TODO: Import stuff
